apiVersion: apps/v1
kind: Deployment
metadata:
  name: artisantek-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: artisantek-app
  template:
    metadata:
      labels:
        app: artisantek-app
    spec:
      containers:
      - name: artisantek-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
