apiVersion: v1
kind: Service
metadata:
  name: artisantek-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: artisantek-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
