replicaCount: 2

image:
  repository: chaitramk23/artisantek-java  # <-- your DockerHub username/image
  tag: jan2026                               # <-- the tag you pushed

service:
  type: LoadBalancer
  port: 5000
