plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  "tag:eks:cluster-name": "devops-eks-cluster"
  "instance-state-name": "running"
keyed_groups:
  - key: tags.Name
    prefix: name_
compose:
  ansible_connection: amazon.aws.aws_ssm   # Use SSM instead of SSH
  ansible_user: ubuntu                    # Default user for EKS AMIs
  ansible_python_interpreter: /usr/bin/python3
