plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  "tag:eks:cluster-name": "devops-eks-cluster"
  "instance-state-name": "running"
compose:
  ansible_user: ubuntu      # <-- for Ubuntu nodes
  ansible_connection: amazon.aws.aws_ssm
