apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hellospring
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hellospring
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8081
