apiVersion: v1
kind: Service
metadata:
  name: hellospring-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hellospring
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
