- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - git
          - docker
          - unzip
          - curl
          - wget
        state: present

    - name: Restart docker
      service:
        name: docker
        state: restarted

  roles:
    - eks_dependencies
